export const ACTIVE_REPOSITORIES_PER_MESSAGE = 100;
export const REPOSITORIES_TO_PROCESS_PER_LAMBDA = 1000;
export const MESSAGES_TO_PROCESS_PER_LAMBDA = Math.floor(REPOSITORIES_TO_PROCESS_PER_LAMBDA / ACTIVE_REPOSITORIES_PER_MESSAGE);
export const MESSAGES_TO_PROCESS_CONCURRENTLY = 100;
